# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: Tristan Partin <tristan@partin.io>

image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  site: tristan957.srht.site
sources:
  - https://git.sr.ht/~tristan957/tristan.partin.io
tasks:
  - check: |
      cd tristan.partin.io
      nix flake check --print-build-logs
  - build: |
      cd tristan.partin.io
      nix develop --command ./scripts/openring/generate.sh
      nix develop --command hugo --baseURL "https://$site"
  - package: |
      branch="$(basename "$GIT_REF")"
      if [ "$branch" != 'master' ]; then
        complete-build
      fi

      cd tristan.partin.io
      tar -C public -cvz . > site.tar.gz
  - upload: |
      cd tristan.partin.io
      nix develop --command hut pages publish -d "$site" site.tar.gz
