image: alpine/edge
packages:
  - go
  - hugo
sources:
  - https://git.sr.ht/~tristan957/tristan.partin.io
tasks:
  - openring: |
      cd tristan.partin.io
      ./scripts/openring/build.sh
  - build: |
      cd tristan.partin.io
      ./scripts/openring/generate.sh
      hugo
