# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Tristan Partin <tristan@partin.io>

image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - git
  - go
  - hugo
  - reuse
  - shellcheck
sources:
  - https://git.sr.ht/~tristan957/tristan.partin.io
tasks:
  - reuse: |
      reuse lint
  - shellcheck: |
      cd tristan.partin.io
      shellcheck $(find scripts/ -type f)
  - openring: |
      cd tristan.partin.io
      ./scripts/openring/build.sh
  - build: |
      cd tristan.partin.io
      ./scripts/openring/generate.sh
      hugo --baseURL=https://tristan957.srht.site
  - package: |
      cd tristan.partin.io
      tar -C public -cvz . > site.tar.gz
  - upload: |
      cd tristan.partin.io
      acurl -f https://pages.sr.ht/publish/tristan957.srht.site -Fcontent=@site.tar.gz
