# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileCopyrightText: Tristan Partin <tristan@partin.io>

image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  DOMAIN: tristan957.srht.site
packages:
  - nixpkgs#devenv
sources:
  - https://git.sr.ht/~tristan957/tristan.partin.io
tasks:
  - check: |
      cd tristan.partin.io
      devenv test
  - build: |
      cd tristan.partin.io
      devenv tasks run openring:generate
      devenv build outputs.site
  - package: |
      branch="$(basename "$GIT_REF")"
      if [ "$branch" != 'master' ]; then
        complete-build
      fi

      devenv build outputs.archive
  - upload: |
      cd tristan.partin.io
      devenv tasks run site:publish --input domain="$DOMAIN"
