# SPDX-License-Identifier: AGPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2024 Tristan Partin <tristan@partin.io>

version = 1
SPDX-HomePage = "https://github.com/tristan957/tristan.partin.io"
SPDX-PackageName = "tristan.partin.io"

[[annotations]]
path = [
    "**.html",
    "**.xml",
    "assets/**",
]
precedence = "override"
SPDX-FileCopyrightText = "Tristan Partin <tristan@partin.io>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    "**.jpg",
    "**.webp",
    ".vscode/**",
    "archetypes/**",
    "layouts/robots.txt",
    "layouts/sitemap.xml",
    "package.json",
    "static/**",
    "vercel.json",
    "webring.txt",
    "yarn.lock",
]
precedence = "override"
SPDX-FileCopyrightText = "Tristan Partin <tristan@partin.io>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "content/**.md",
]
precedence = "override"
SPDX-FileCopyrightText = "Tristan Partin <tristan@partin.io>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
